spring.application.name=employee-management

# Database connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:3307/postgres
spring.datasource.username=postgres
spring.datasource.password=2001
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.default_schema=Employee_app
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true