apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: employee-management:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 9007

---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-service
  namespace: app1
spec:
  selector:
    app: employee-app
  ports:
    - port: 9007
      targetPort: 9007
  type: NodePort